src/locations/urls.py
from django.urls import path
from . import views

app_name = 'locations'
urlpatterns = [
    path('', views.StateListView.as_view(), name='state_list'),
    path('add_state', views.AddStateView.as_view(), name='add_state'),
    path('update_state/<int:pk>',
         views.StateUpdateView.as_view(), name='update_state'),

    # Locality views
    path('localities/', views.LocalityListView.as_view(), name='locality_list'),
    path('add_locality/', views.AddLocalityView.as_view(), name='add_locality'),
    path('update_locality/<int:pk>',
         views.LocalityUpdateView.as_view(), name='update_locality'),
]

src/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('profiles.urls')),
    path('locations/', include('locations.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/profiles/urls.py
from django.urls import path 
from . import views

app_name = 'profiles'

urlpatterns = [
	path('', views.dashboard, name='dashboard'),
]

src/locations/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse


class State(models.Model):
    name = models.CharField(verbose_name='الولاية', max_length=50)
    slug = models.SlugField(blank=True, null=True, editable=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.slug == None:
            self.slug = slugify(self.name, allow_unicode=True)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('locations:state_list')


class Locality(models.Model):
    name = models.CharField(verbose_name='المحلية', max_length=50)
    state = models.ForeignKey(
        State, verbose_name='الولاية', on_delete=models.CASCADE)
    slug = models.SlugField(blank=True, null=True, editable=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.slug == None:
            self.slug = slugify(self.name, allow_unicode=True)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('locations:locality_list')

src/profiles/models.py
from django.db import models

# Create your models here.

src/locations/forms.py
from django import forms
from .models import State, Locality


class StateForm(forms.ModelForm):
    class Meta:
        model = State
        fields = ['name']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update(
            {'class': 'block w-full px-4 py-2 mt-2 text-gray-700 bg-white border border-gray-300 rounded-md dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600 focus:border-blue-500 dark:focus:border-blue-500 focus:outline-none focus:ring'})


class LocalityForm(forms.ModelForm):
    class Meta:
        model = Locality
        fields = ['name', 'state']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update(
            {'class': 'block w-full px-4 py-2 mt-2 text-gray-700 bg-white border border-gray-300 rounded-md dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600 focus:border-blue-500 dark:focus:border-blue-500 focus:outline-none focus:ring'})
        self.fields['state'].widget.attrs.update(
            {'class': 'block w-full px-4 py-2 mt-2 text-gray-700 bg-white border border-gray-300 rounded-md dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600 focus:border-blue-500 dark:focus:border-blue-500 focus:outline-none focus:ring'})

src/locations/views.py
# from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView

from .models import State, Locality
from .forms import StateForm, LocalityForm


class AddStateView(CreateView):
    form_class = StateForm
    context_object_name = 'state'
    template_name = 'locations/add_state.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'ولاية جديدة'
        context['header'] = 'أضافة ولاية '
        context['action'] = 'حفظ'
        return context


class StateListView(ListView):
    model = State
    template_name = 'locations/state_list.html'
    context_object_name = 'states'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'قائمة الولايات'
        context['header'] = 'الولايات'
        return context


class StateUpdateView(UpdateView):
    model = State
    form_class = StateForm
    context_object_name = 'state'
    template_name = 'locations/add_state.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'تعديل ولاية'
        context['header'] = 'تعديل ولاية --'
        context['action'] = 'تعديل'
        return context


class AddLocalityView(CreateView):
    form_class = LocalityForm
    context_object_name = 'locality'
    template_name = 'locations/add_locality.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'محلية جديدة'
        context['header'] = 'أضافة محلية '
        context['action'] = 'حفظ'
        return context


class LocalityListView(ListView):
    model = Locality
    template_name = 'locations/locality_list.html'
    context_object_name = 'localities'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'قائمة المحليات'
        context['header'] = 'المحليات'
        return context


class LocalityUpdateView(UpdateView):
    model = Locality
    form_class = LocalityForm
    context_object_name = 'locality'
    template_name = 'locations/add_locality.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'تعديل محلية'
        context['header'] = 'تعديل محلية --'
        context['action'] = 'تعديل'
        return context

src/profiles/views.py
from django.shortcuts import render

def dashboard(request):
	return render(request, 'base.html')

src/templates/base.html
{% load static %}
<!doctype html>
<html dir="rtl">
<head>
  <!-- ... -->
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href="{% static 'css/tailwind_css/dist/css/style.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <title>{% block title %}{% endblock %}</title>
</head>
<body class="bg-white">
  <div class="flex justify-between p-3 bg-white bg-gradient-to-l from-green-800 to-green-100">
    <div class="px-5 text-2xl leading-relaxed tracking-wide text-green-500 font-extralight"></div>
    <div>
      <button class="px-5 py-2 ml-3 text-sm text-green-200 bg-green-500 border-green-800 rounded-lg shadow-lg">دخول</button>
      <button class="px-5 py-2 text-sm text-green-200 bg-green-500 border-green-800 rounded-lg shadow-lg">تسجيل</button>
    </div>
  </div>

  <div class="grid grid-cols-4 gap-4 mt-4 mr-4">
    <div class="w-1/6 h-64 bg-blue-300">

    <div class="flex flex-col w-64 h-screen px-4 bg-white border-r shadow-xl dark:bg-gray-800 dark:border-gray-600 rounded-xl">
        <h2 class="text-xl font-semibold text-gray-400 dark:text-white">القائمة الرئيسية</h2>

        <!-- <div class="relative mt-6">
            <span class="absolute inset-y-0 left-0 flex items-center pl-3">
                <svg class="w-5 h-5 text-gray-400" viewBox="0 0 24 24" fill="none">
                    <path d="M21 21L15 15M17 10C17 13.866 13.866 17 10 17C6.13401 17 3 13.866 3 10C3 6.13401 6.13401 3 10 3C13.866 3 17 6.13401 17 10Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
                </svg>
            </span>

            <input type="text" class="w-full py-3 pl-10 pr-4 text-gray-700 bg-white border border-gray-300 rounded-md dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600 focus:border-blue-500 dark:focus:border-blue-500 focus:outline-none focus:ring" placeholder="Search"/>
        </div> -->

        <div class="flex flex-col justify-between flex-1 mt-6 ">
            <nav>
                <a class="flex items-center px-4 py-1 text-gray-700 bg-gray-200 rounded-md dark:bg-gray-700 dark:text-gray-200" href="#">
                    <svg class="w-5 h-5" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M19 11H5M19 11C20.1046 11 21 11.8954 21 13V19C21 20.1046 20.1046 21 19 21H5C3.89543 21 3 20.1046 3 19V13C3 11.8954 3.89543 11 5 11M19 11V9C19 7.89543 18.1046 7 17 7M5 11V9C5 7.89543 5.89543 7 7 7M7 7V5C7 3.89543 7.89543 3 9 3H15C16.1046 3 17 3.89543 17 5V7M7 7H17" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                    </svg>

                    <span class="mx-4 font-medium text-blue-400">الأعدادات</span>
                </a>
                <hr class="my-2 dark:border-gray-600" />
                <a class="flex items-center px-4 py-1 mt-3 text-gray-600 transition-colors duration-200 transform rounded-md dark:text-gray-400 hover:bg-gray-200 dark:hover:bg-gray-700 dark:hover:text-gray-200 hover:text-gray-700" href="#">
                    <svg class="w-5 h-5" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M16 7C16 9.20914 14.2091 11 12 11C9.79086 11 8 9.20914 8 7C8 4.79086 9.79086 3 12 3C14.2091 3 16 4.79086 16 7Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                    <path d="M12 14C8.13401 14 5 17.134 5 21H19C19 17.134 15.866 14 12 14Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                    </svg>

                    <span class="mx-4 font-medium text-blue-400">الحسابات</span>
                </a>
<hr class="my-2 dark:border-gray-600" />
                <a class="flex items-center px-4 py-1 mt-3 text-gray-600 transition-colors duration-200 transform rounded-md dark:text-gray-400 hover:bg-gray-200 dark:hover:bg-gray-700 dark:hover:text-gray-200 hover:text-gray-700" href="#">
                    <svg class="w-5 h-5" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M15 5V7M15 11V13M15 17V19M5 5C3.89543 5 3 5.89543 3 7V10C4.10457 10 5 10.8954 5 12C5 13.1046 4.10457 14 3 14V17C3 18.1046 3.89543 19 5 19H19C20.1046 19 21 18.1046 21 17V14C19.8954 14 19 13.1046 19 12C19 10.8954 19.8954 10 21 10V7C21 5.89543 20.1046 5 19 5H5Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                    </svg>

                    <span class="mx-4 font-medium text-blue-400">الولايات & المحليات ..</span>
                </a>
<hr class="my-2 dark:border-gray-600" />
                <a class="flex items-center px-4 py-1 mt-3 text-gray-600 transition-colors duration-200 transform rounded-md dark:text-gray-400 hover:bg-gray-200 dark:hover:bg-gray-700 dark:hover:text-gray-200 hover:text-gray-700" href="#">
                    <svg class="w-5 h-5" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M10.3246 4.31731C10.751 2.5609 13.249 2.5609 13.6754 4.31731C13.9508 5.45193 15.2507 5.99038 16.2478 5.38285C17.7913 4.44239 19.5576 6.2087 18.6172 7.75218C18.0096 8.74925 18.5481 10.0492 19.6827 10.3246C21.4391 10.751 21.4391 13.249 19.6827 13.6754C18.5481 13.9508 18.0096 15.2507 18.6172 16.2478C19.5576 17.7913 17.7913 19.5576 16.2478 18.6172C15.2507 18.0096 13.9508 18.5481 13.6754 19.6827C13.249 21.4391 10.751 21.4391 10.3246 19.6827C10.0492 18.5481 8.74926 18.0096 7.75219 18.6172C6.2087 19.5576 4.44239 17.7913 5.38285 16.2478C5.99038 15.2507 5.45193 13.9508 4.31731 13.6754C2.5609 13.249 2.5609 10.751 4.31731 10.3246C5.45193 10.0492 5.99037 8.74926 5.38285 7.75218C4.44239 6.2087 6.2087 4.44239 7.75219 5.38285C8.74926 5.99037 10.0492 5.45193 10.3246 4.31731Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                    <path d="M15 12C15 13.6569 13.6569 15 12 15C10.3431 15 9 13.6569 9 12C9 10.3431 10.3431 9 12 9C13.6569 9 15 10.3431 15 12Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                    </svg>

                    <span class="mx-4 font-medium text-blue-400">المستخدمبن</span>
                </a>

                <hr class="my-2 dark:border-gray-600" />

                <a class="flex items-center px-4 py-1 mt-3 text-gray-600 transition-colors duration-200 transform rounded-md dark:text-gray-400 hover:bg-gray-200 dark:hover:bg-gray-700 dark:hover:text-gray-200 hover:text-gray-700" href="#">
                    <svg class="w-5 h-5" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M15 5V7M15 11V13M15 17V19M5 5C3.89543 5 3 5.89543 3 7V10C4.10457 10 5 10.8954 5 12C5 13.1046 4.10457 14 3 14V17C3 18.1046 3.89543 19 5 19H19C20.1046 19 21 18.1046 21 17V14C19.8954 14 19 13.1046 19 12C19 10.8954 19.8954 10 21 10V7C21 5.89543 20.1046 5 19 5H5Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                    </svg>

                    <span class="mx-4 font-medium text-blue-400">السحب والتخزين</span>
                </a>
<hr class="my-2 dark:border-gray-600" />
                <a class="flex items-center px-4 py-1 mt-3 text-gray-600 transition-colors duration-200 transform rounded-md dark:text-gray-400 hover:bg-gray-200 dark:hover:bg-gray-700 dark:hover:text-gray-200 hover:text-gray-700" href="#">
                    <svg class="w-5 h-5" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M10.3246 4.31731C10.751 2.5609 13.249 2.5609 13.6754 4.31731C13.9508 5.45193 15.2507 5.99038 16.2478 5.38285C17.7913 4.44239 19.5576 6.2087 18.6172 7.75218C18.0096 8.74925 18.5481 10.0492 19.6827 10.3246C21.4391 10.751 21.4391 13.249 19.6827 13.6754C18.5481 13.9508 18.0096 15.2507 18.6172 16.2478C19.5576 17.7913 17.7913 19.5576 16.2478 18.6172C15.2507 18.0096 13.9508 18.5481 13.6754 19.6827C13.249 21.4391 10.751 21.4391 10.3246 19.6827C10.0492 18.5481 8.74926 18.0096 7.75219 18.6172C6.2087 19.5576 4.44239 17.7913 5.38285 16.2478C5.99038 15.2507 5.45193 13.9508 4.31731 13.6754C2.5609 13.249 2.5609 10.751 4.31731 10.3246C5.45193 10.0492 5.99037 8.74926 5.38285 7.75218C4.44239 6.2087 6.2087 4.44239 7.75219 5.38285C8.74926 5.99037 10.0492 5.45193 10.3246 4.31731Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                    <path d="M15 12C15 13.6569 13.6569 15 12 15C10.3431 15 9 13.6569 9 12C9 10.3431 10.3431 9 12 9C13.6569 9 15 10.3431 15 12Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                    </svg>

                    <span class="mx-4 font-medium text-blue-400">المكلفين</span>
                </a>
                <hr class="my-2 dark:border-gray-600" />
            </nav>

            <!-- <div class="flex items-center px-4 -mx-2">
                <img class="object-cover mx-2 rounded-full h-9 w-9" src="https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80" alt="avatar"/>
                <h4 class="mx-2 font-medium text-gray-800 dark:text-gray-200 hover:underline">John Doe</h4>
            </div> -->
        </div>
    </div>
    </div>
    <div class="h-64 col-span-2">
      {% block content %}{% endblock %}
    </div>
    <div class="h-64">
    </div>
  </div>
</body>
</html>

src/templates/locations/add_locality.html
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
  <h2 class="px-5 py-3 text-lg tracking-wider text-gray-600 shadow-xl font-base text-bold">{{ header }}</h2>
  <div class="px-6 py-4 mx-auto mt-2 bg-white border shadow-xl h-42 rounded-xl">
    <form method="post">
      {% csrf_token %}
           {{ form }}
      <button type="submit" class="flex justify-between px-5 py-2 mt-4 font-thin text-white bg-blue-500 border rounded-lg ">
        <span class="ml-5 mr-5">{{ action }}</span> 
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 14v6m-3-3h6M6 10h2a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v2a2 2 0 002 2zm10 0h2a2 2 0 002-2V6a2 2 0 00-2-2h-2a2 2 0 00-2 2v2a2 2 0 002 2zM6 20h2a2 2 0 002-2v-2a2 2 0 00-2-2H6a2 2 0 00-2 2v2a2 2 0 002 2z"></path></svg>
      </button>
    </form>
  </div>
{% endblock %}

src/templates/locations/add_state.html
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
  <h2 class="px-5 py-3 text-lg tracking-wider text-gray-600 shadow-xl font-base text-bold">{{ header }}</h2>
  <div class="px-6 py-4 mx-auto mt-2 bg-white border shadow-xl h-42 rounded-xl">
    <form method="post">
      {% csrf_token %}
           {{ form }}
      <button type="submit" class="flex justify-between px-5 py-2 mt-4 font-thin text-white bg-blue-500 border rounded-lg ">
        <span class="ml-5 mr-5">{{ action }}</span> 
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 14v6m-3-3h6M6 10h2a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v2a2 2 0 002 2zm10 0h2a2 2 0 002-2V6a2 2 0 00-2-2h-2a2 2 0 00-2 2v2a2 2 0 002 2zM6 20h2a2 2 0 002-2v-2a2 2 0 00-2-2H6a2 2 0 00-2 2v2a2 2 0 002 2z"></path></svg>
      </button>
    </form>
  </div>
{% endblock %}

src/templates/locations/locality_list.html
{% extends 'base.html' %}
{% block title %}
    {{ title }}
{% endblock %}
{% block content %}
    <h2 class="px-10 py-3 text-xl shadow-xl">{{ header }}</h2>
    <hr class="my-3 dark:border-gray-900" />
    <a class="px-5 py-1 ml-10 bg-blue-400 border rounded-lg shadow-xl text-blue-10" href="{% url 'locations:add_locality' %}">أضافة جديد</a>
    {% if localities %}
       
        {% for locality in localities %}
            <div class="flex justify-between px-10 py-4 mt-3 bg-gray-100 border rounded-lg shadowlg">
                <div class="">
                    <span class="ml-10">{{ locality.id }} - </span><span class="ml-10">{{ locality.name }}</span>
                    <span>(ولاية)  - {{ locality.state.name }}</span>
                </div>
                <div>
                    <a class="px-5 py-1 ml-10 bg-blue-400 border rounded-lg shadow-xl text-blue-10" 
                    href="{% url 'locations:update_locality' locality.id %}">
                        <span>تعديل</span>
                        
                    </a>
                    <a class="px-5 py-1 ml-10 bg-red-400 border rounded-lg shadow-xl text-red-10" href="http://">حذف</a>
                </div>
            </div>
        {% endfor %}
    {% else %}
    {% endif %}
{% endblock %}

src/templates/locations/state_list.html
{% extends 'base.html' %}
{% block title %}
    {{ title }}
{% endblock %}
{% block content %}
    <h2 class="px-10 py-3 text-xl shadow-xl">{{ header }}</h2>
    <hr class="my-3 dark:border-gray-900" />
    <a class="px-5 py-1 ml-10 bg-blue-400 border rounded-lg shadow-xl text-blue-10" href="{% url 'locations:add_state' %}">أضافة جديد</a>
    {% if states %}
       
        {% for state in states %}
            <div class="flex justify-between px-10 py-4 mt-3 bg-gray-100 border rounded-lg shadowlg">
                <div class="">
                    <span class="ml-10">{{ state.id }} - </span><span>{{ state.name }}</span>
                </div>
                <div>
                    <a class="px-5 py-1 ml-10 bg-blue-400 border rounded-lg shadow-xl text-blue-10" 
                    href="{% url 'locations:update_state' state.id %}">
                        <span>تعديل</span>
                        
                    </a>
                    <a class="px-5 py-1 ml-10 bg-red-400 border rounded-lg shadow-xl text-red-10" href="http://">حذف</a>
                </div>
            </div>
        {% endfor %}
    {% else %}
    {% endif %}
{% endblock %}